services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD} 
      MARIADB_DATABASE: ${DB_NAME:-funda_pineda_db}
      MARIADB_USER: ${DB_USER:-root}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://${DB_USER:-root}:${DB_PASSWORD}@${DB_HOST:-db}/${DB_NAME:-funda_pineda_db}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_STARTTLS: ${MAIL_STARTTLS}
      MAIL_SSL_TLS: ${MAIL_SSL_TLS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

      CONTACT_NOTIFICATION_EMAIL: ${CONTACT_NOTIFICATION_EMAIL}

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://${BACKEND_HOST:-tu-ip-aws}:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    

volumes:
  mariadb_data: